class ProductModel {
  String name;
  String image;
  int number;
  int amountExisting;
  int amountTrust;
  bool importSelected = false;
  bool exportSelected = false;

  ProductModel(
      {this.name,
      this.image,
      this.number,
      this.amountExisting,
      this.amountTrust,
      this.exportSelected,
      this.importSelected});
}

List<ProductModel> primaryBrouduct = [
  ProductModel(
    name: 'براغي',
    image: "assets/images/primary/1.PNG",
    amountExisting: 1020,
    amountTrust: 102,
    number: 4501,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "بواري حديد",
    image: "assets/images/primary/2.PNG",
    amountExisting: 2000,
    amountTrust: 204,
    number: 2342,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "رومانات",
    image: "assets/images/primary/3.PNG",
    amountExisting: 3020,
    amountTrust: 300,
    number: 3245,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "صاج حديد",
    image: "assets/images/primary/4.PNG",
    amountExisting: 4040,
    amountTrust: 440,
    number: 4245,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "عزق",
    image: "assets/images/primary/5.PNG",
    amountExisting: 5060,
    amountTrust: 504,
    number: 425,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "مطاط صناعي",
    image: "assets/images/primary/6.PNG",
    amountExisting: 6400,
    amountTrust: 600,
    number: 2586,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "مطاط طبيعي",
    image: "assets/images/primary/7.PNG",
    amountExisting: 7030,
    amountTrust: 720,
    number: 4567,
    importSelected: false,
    exportSelected: false,
  ),
];
List<ProductModel> secandaryBrouduct = [
  ProductModel(
    name: 'جناح',
    image: "assets/images/secandary/1.PNG",
    amountExisting: 1030,
    amountTrust: 104,
    number: 2541,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "جنط",
    image: "assets/images/secandary/2.PNG",
    amountExisting: 2020,
    amountTrust: 270,
    number: 2456,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "طبشة",
    image: "assets/images/secandary/3.PNG",
    amountExisting: 3060,
    amountTrust: 340,
    number: 3258,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "كوشوك",
    image: "assets/images/secandary/4.PNG",
    amountExisting: 4070,
    amountTrust: 410,
    number: 4534,
    importSelected: false,
    exportSelected: false,
  ),
];

List<ProductModel> thirdlyBrouduct = [
  ProductModel(
    name: 'ملقط ثابت',
    image: "assets/images/thirdly/1.PNG",
    amountExisting: 1020,
    amountTrust: 170,
    number: 8521,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "ملقط متحرك",
    image: "assets/images/thirdly/2.PNG",
    amountExisting: 2020,
    amountTrust: 201,
    number: 4562,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "ملقط متحرك بفرام",
    image: "assets/images/thirdly/3.PNG",
    amountExisting: 3020,
    amountTrust: 380,
    number: 0253,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "دولاب",
    image: "assets/images/thirdly/5112.PNG",
    amountExisting: 4300,
    amountTrust: 407,
    number: 5112,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "دولاب",
    image: "assets/images/thirdly/5115.PNG",
    amountExisting: 5600,
    amountTrust: 503,
    number: 5115,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "دولاب",
    image: "assets/images/thirdly/5120.PNG",
    amountExisting: 6030,
    amountTrust: 670,
    number: 5120,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "دولاب",
    image: "assets/images/thirdly/5135.PNG",
    amountExisting: 7020,
    amountTrust: 706,
    number: 5135,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "دولاب",
    image: "assets/images/thirdly/5150.PNG",
    amountExisting: 7010,
    amountTrust: 706,
    number: 5150,
    importSelected: false,
    exportSelected: false,
  ),
];
List<ProductModel> allProduct = [
  ProductModel(
    name: 'براغي',
    image: "assets/images/primary/1.PNG",
    amountExisting: 1020,
    amountTrust: 102,
    number: 4501,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "بواري حديد",
    image: "assets/images/primary/2.PNG",
    amountExisting: 2000,
    amountTrust: 204,
    number: 2342,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "رومانات",
    image: "assets/images/primary/3.PNG",
    amountExisting: 3020,
    amountTrust: 300,
    number: 3245,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "صاج حديد",
    image: "assets/images/primary/4.PNG",
    amountExisting: 4040,
    amountTrust: 440,
    number: 4245,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "عزق",
    image: "assets/images/primary/5.PNG",
    amountExisting: 5060,
    amountTrust: 504,
    number: 425,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "مطاط صناعي",
    image: "assets/images/primary/6.PNG",
    amountExisting: 6400,
    amountTrust: 600,
    number: 2586,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "مطاط طبيعي",
    image: "assets/images/primary/7.PNG",
    amountExisting: 7030,
    amountTrust: 720,
    number: 4567,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: 'جناح',
    image: "assets/images/secandary/1.PNG",
    amountExisting: 1030,
    amountTrust: 104,
    number: 2541,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "جنط",
    image: "assets/images/secandary/2.PNG",
    amountExisting: 2020,
    amountTrust: 270,
    number: 2456,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "طبشة",
    image: "assets/images/secandary/3.PNG",
    amountExisting: 3060,
    amountTrust: 340,
    number: 3258,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "كوشوك",
    image: "assets/images/secandary/4.PNG",
    amountExisting: 4070,
    amountTrust: 410,
    number: 4534,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: 'ملقط ثابت',
    image: "assets/images/thirdly/1.PNG",
    amountExisting: 1020,
    amountTrust: 170,
    number: 8521,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "ملقط متحرك",
    image: "assets/images/thirdly/2.PNG",
    amountExisting: 2020,
    amountTrust: 201,
    number: 4562,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "ملقط متحرك بفرام",
    image: "assets/images/thirdly/3.PNG",
    amountExisting: 3020,
    amountTrust: 380,
    number: 0253,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "دولاب",
    image: "assets/images/thirdly/5112.PNG",
    amountExisting: 4300,
    amountTrust: 407,
    number: 5112,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "دولاب",
    image: "assets/images/thirdly/5115.PNG",
    amountExisting: 5600,
    amountTrust: 503,
    number: 5115,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "دولاب",
    image: "assets/images/thirdly/5120.PNG",
    amountExisting: 6030,
    amountTrust: 670,
    number: 5120,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "دولاب",
    image: "assets/images/thirdly/5135.PNG",
    amountExisting: 7020,
    amountTrust: 706,
    number: 5135,
    importSelected: false,
    exportSelected: false,
  ),
  ProductModel(
    name: "دولاب",
    image: "assets/images/thirdly/5150.PNG",
    amountExisting: 7010,
    amountTrust: 706,
    number: 5150,
    importSelected: false,
    exportSelected: false,
  ),
];
/// from onaisa 